---
language: python
python:
- '3.4'
before_install: openssl aes-256-cbc -K $encrypted_4e9a002c9ef6_key -iv $encrypted_4e9a002c9ef6_iv -in secrets.py.enc -out RateMyLandlord/secrets.py -d 
install: pip install -r requirements.txt
before_script:
- python manage.py runserver &
script: python manage.py test
